name: Savvy
description: For everything technical and interesting
author: "Kaushik"
meta_description: "another blog"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: "/savvy"
domain_name: "kaushik.me"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""

# Disqus config
disqus-shortname: ""
